const KOSA_KATA_GAME = {
    "madya": [
        { krama: "ABRIT", hint: "Merah." },
        { krama: "GRIYA", hint: "rumah." },
        { krama: "SIRAH", hint: "Anggota badan paling atas." },
        { krama: "ASTA", hint: "tangan." },
        { krama: "NEDHA", hint: "Makan." },
        { krama: "SARE", hint: "tidur." },
        { krama: "ADUS", hint: "Mandi." },
        { krama: "NYUWUN", hint: "Meminta." },
        { krama: "TIYANG", hint: "Orang." },
        { krama: "DHATENG", hint: "Datang." },
        { krama: "TEBIH", hint: "Jauh." },
        { krama: "BETHAK", hint: "Menanak nasi." },
        { krama: "BUDHAL", hint: "Berangkat" },
        { krama: "ABEN", hint: "Mengadu." },
        { krama: "AJANG", hint: "Tempat/piring." },
        { krama: "KULA", hint: "Saya." },
        { krama: "WONTEN", hint: "Ada." },
        { krama: "YOGA", hint: "Anak(kepemilikan)." },
        { krama: "TUMUT", hint: "Ikut" },
        { krama: "SIYANG", hint: "Siang." },
        { krama: "MANGGA", hint: "Silahkan." },
        { krama: "RAMPUNG", hint: "Teman." },
        { krama: "PURUN", hint: "Bersedia/mau" },
        { krama: "ALIT", hint: "Kecil" },
        { krama: "CEKAP", hint: "Cukup" },
        { krama: "INGGIL", hint: "Tinggi" },
        { krama: "DRIJI", hint: "Jari (anggota tubuh)" },
        { krama: "SANES", hint: "Bukan" },
        { krama: "GADHAH", hint: "Punya" },
        { krama: "ELING", hint: "Ingat" },
        { krama: "EMBAH", hint: "Nenek - Kakek" },
        { krama: "MENDHET", hint: "Ambil" },
        { krama: "APUNTEN", hint: "Maaf" },
        { krama: "SEGAWON", hint: "Bersedia" },
        { krama: "NYUKANI", hint: "Bersedia" },
        { krama: "WANGSUL", hint: "Bersedia" },
        { krama: "BENJING", hint: "Besok" },
        { krama: "RIYIN", hint: "Dulu" },
        { krama: "RAMPUNG", hint: "Selesai" },
        { krama: "SUMEREP", hint: "Tahu / mengerti" },
        { krama: "PIYAMBAK", hint: "Sendiri" },
        { krama: "KALA", hint: "Ketika" },
        { krama: "YATRA", hint: "Uang" },
        { krama: "DINTEN", hint: "Hari" },
        { krama: "DEKEK", hint: "Taruh/menaruh" },
        { krama: "DERENG", hint: "Belum" },
        { krama: "NEMBE", hint: "Baru saja" },
        { krama: "JANGKEP", hint: "Lengkap" },
    ],
    "inggil": [
        { krama: "PUNIKA", hint: "Ini" },
        { krama: "PISUH", hint: "Mengumpat/memaki." },
        { krama: "PANJENENGAN", hint: "Anda" },
        { krama: "SESAWI", hint: "Sayuran hijau yang sering dimasak (sawi)." },
        { krama: "KAPARENG", hint: "Diperbolehkan." },
        { krama: "JUMENENG", hint: "Berdiri." },
        { krama: "PALINGGIHAN", hint: "Tempat duduk/kursi." },
        { krama: "PASARAN", hint: "Hari-hari dalam penanggalan Jawa (Legi, Pahing, dsb.)." },
        { krama: "SAMPUR", hint: "Selendang panjang untuk menari." },
        { krama: "SIRAM", hint: "Mandi" },
        { krama: "TEBIH", hint: "Jauh." },
        { krama: "MENAWI", hint: "Kalau." },
        { krama: "TINDAK", hint: "Berangkat/jalan" },
        { krama: "ASREP", hint: "Dingin." },
        { krama: "SADE", hint: "Jual." },
        { krama: "AWRAT", hint: "Berat." },
        { krama: "IMBA", hint: "Alis." },
        { krama: "PINARAK", hint: "Mampir/singgah" },
        { krama: "AMARGI", hint: "Sebab/akibat." },
        { krama: "SAE", hint: "Bagus." },
        { krama: "ASMA", hint: "Nama." },
        { krama: "KERSA", hint: "Mau" },
        { krama: "MENIKA", hint: "Itu" },
        { krama: "SAGED", hint: "Bisa" },
        { krama: "WIYAR", hint: "Luas" },
        { krama: "PUNDHUT", hint: "Ambil" },
        { krama: "NGAOS", hint: "Mengaji" },
        { krama: "DANGU", hint: "Lama" },
        { krama: "LEBET", hint: "didalam/kedalam" },
        { krama: "KALIH", hint: "Dua" },
        { krama: "LANGKUNG", hint: "Lebih" },
        { krama: "MAJENG", hint: "Maju" },
        { krama: "MARGI", hint: "Karena" },
        { krama: "MIYOS", hint: "Keluar" },
        { krama: "MRIKSANI", hint: "Melihat" },
        { krama: "MARINGAKEN", hint: "Meletakkan" },
        { krama: "ANGSAL", hint: "Mendapatkan" },
        { krama: " MBOTEN", hint: "Tidak" },
        { krama: "PEKEN", hint: "Pasar" },
        { krama: "LEPAT", hint: "Salah" },
        { krama: "SINTEN", hint: "Siapa" },
        { krama: "SAKEDHAP", hint: "Sebentar" },
        { krama: "KONDUR", hint: "Pulang" },
        { krama: "ATUR", hint: "Panggil" },
        { krama: "WATAWIS", hint: "Antara/kira-kira" },
        { krama: "DIPUNSUKANI", hint: "Dikasih" },
        { krama: "PRIYANTUN", hint: "Orang" },
        { krama: "WETAH", hint: "Utuh/bertambah" },
        { krama: "SETUNGGAL", hint: "Satu" },
        { krama: "ENJING", hint: "Pagi" },
        { krama: "NGASTA", hint: "Membuat" },

        
    ]
};