// data.js
// Kumpulan data kosakata Bahasa Jawa Krama Alus
const KOSA_KATA_GAME = {
    "madya": [
        { krama: "ABRIT", hint: "Merah." },
        { krama: "GRIYA", hint: "rumah." },
        { krama: "SIRAH", hint: "Anggota badan paling atas." },
        { krama: "ASTA", hint: "tangan." },
        { krama: "NEDHA", hint: "Makan." },
        { krama: "SARE", hint: "tidur." },
        { krama: "ADUS", hint: "Mandi." },
        { krama: "NYUWUN", hint: "Meminta." },
        { krama: "TIYANG", hint: "Orang." },
        { krama: "DHATENG", hint: "Datang." },
        { krama: "TEBIH", hint: "Jauh." },
        { krama: "BETHAK", hint: "Menanak nasi." },
        { krama: "BUDHAL", hint: "Berangkat" },
        { krama: "ABEN", hint: "Mengadu." },
        { krama: "AJANG", hint: "Tempat/piring." },
        { krama: "KULA", hint: "Saya." },
        { krama: "WONTEN", hint: "Ada." },
        { krama: "YOGA", hint: "Anak(kepemilikan)." },
        { krama: "TUMUT", hint: "Ikut" },
        { krama: "SIYANG", hint: "Siang." },
        { krama: "MANGGA", hint: "Silahkan." },
        { krama: "RAMPUNG", hint: "Teman." },
        { krama: "PURUN", hint: "Bersedia" },
    ],
    "inggil": [
        { krama: "PRINGGASELA", hint: "Pagar di sekeliling rumah." },
        { krama: "PISUH", hint: "Mengumpat/memaki." },
        { krama: "PANJENENGAN", hint: "Anda" },
        { krama: "SESAWI", hint: "Sayuran hijau yang sering dimasak (sawi)." },
        { krama: "KAPARENG", hint: "Diperbolehkan." },
        { krama: "JUMENENG", hint: "Berdiri." },
        { krama: "PALINGGIHAN", hint: "Tempat duduk/kursi." },
        { krama: "PASARAN", hint: "Hari-hari dalam penanggalan Jawa (Legi, Pahing, dsb.)." },
        { krama: "SAMPUR", hint: "Selendang panjang untuk menari." },
        { krama: "SIRAM", hint: "Mandi" },
        { krama: "TEBIH", hint: "Jauh." },
        { krama: "MENAWI", hint: "Kalau." },
        { krama: "TINDAK", hint: "Berangkat." },
        { krama: "ASREP", hint: "Dingin." },
        { krama: "SADE", hint: "Jual." },
        { krama: "AWRAT", hint: "Berat." },
        { krama: "IMBA", hint: "Alis." },
        { krama: "PINARAK", hint: "Mampir/singgah" },
        { krama: "AMARGI", hint: "Sebab/akibat." },
        { krama: "SAE", hint: "Bagus." },
        { krama: "ASMA", hint: "Nama." },
        { krama: "KERSA", hint: "Mau" },
    ]
};